<a href="https://colab.research.google.com/github/prasanthsret/machine-learning/blob/main/ML_E8122015_CA1_Q2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

QUESTION NO : 2
A hospital wants to develop a model to predict the severity of a patient's condition
upon admission. The hospital has data on patients' demographics, medical history,
and vital signs at admission. The hospital would like to use this information to
predict whether the patient's condition is mild, moderate, or severe.

In [ ]:
#Hospital dataset

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn import preprocessing

In [ ]:
p=pd.read_csv("/content/patient_data.csv")

In [ ]:
p

Age  Gender  Ethnicity  BMI  Blood Pressure (systolic)  \
0    45    Male  Caucasian   23                        120   
1    30  Female   Hispanic   27                        135   
2    65    Male    African   32                        150   
3    50  Female  Caucasian   29                        140   
4    28    Male      Asian   25                        115   
5    60  Female    African   35                        170   
6    40    Male   Hispanic   26                        130   
7    35  Female      Asian   24                        118   
8    55    Male  Caucasian   31                        142   
9    75  Female   Hispanic   26                        130   
10   48    Male    African   33                        160   
11   27  Female  Caucasian   22                        110   
12   58    Male      Asian   30                        135   
13   32    Male      Asian   22                        120   
14   45  Female      Black   28                        136   
15   58    Male      White   34                        150   
16   72  Female   Hispanic   26                        128   
17   41    Male      Black   30                        142   
18   45    Male      Asian   24                        120   
19   65  Female  Caucasian   28                        140   
20   30    Male    African   32                        130   
21   58  Female   Hispanic   26                        125   

    Blood Pressure (diastolic)  Heart Rate  Respiratory Rate  \
0                           80          75                16   
1                           90          80                18   
2                          100          90                20   
3                           95          70                14   
4                           75          80                16   
5                          110          85                18   
6                           85          75                16   
7                           78          70                14   
8                           95          80                16   
9                           85          80                20   
10                         100          90                20   
11                          72          75                14   
12                          90          75                16   
13                          80          75                16   
14                          92          80                18   
15                         100          70                20   
16                          84          85                14   
17                          94          77                16   
18                          80          70                16   
19                          90          80                20   
20                          85          85                18   
21                          80          75                16   

    Oxygen Saturation Level Chronic Conditions     Medications  \
0                        98               None            None   
1                        95       Hypertension            None   
2                        92           Diabetes         Insulin   
3                        96               None  Blood thinners   
4                        97               None            None   
5                        90       Hypertension            None   
6                        98               None            None   
7                        96               None            None   
8                        94      Heart Disease            None   
9                        92               None            None   
10                       92           Diabetes         Insulin   
11                       96               None            None   
12                       94               None            None   
13                       98               None            None   
14                       95       Hypertension            None   
15                       90           Diabetes  

In [ ]:
p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   Age                         22 non-null     int64 
 1   Gender                      22 non-null     object
 2   Ethnicity                   22 non-null     object
 3   BMI                         22 non-null     int64 
 4   Blood Pressure (systolic)   22 non-null     int64 
 5   Blood Pressure (diastolic)  22 non-null     int64 
 6   Heart Rate                  22 non-null     int64 
 7   Respiratory Rate            22 non-null     int64 
 8   Oxygen Saturation Level     22 non-null     int64 
 9   Chronic Conditions          22 non-null     object
 10  Medications                 22 non-null     object
 11  Lab Test Results            22 non-null     object
 12  Chief Complaint             22 non-null     object
 13  Severity                    22 non-null     object
d

In [ ]:
p.head(5)

Age  Gender  Ethnicity  BMI  Blood Pressure (systolic)  \
0   45    Male  Caucasian   23                        120   
1   30  Female   Hispanic   27                        135   
2   65    Male    African   32                        150   
3   50  Female  Caucasian   29                        140   
4   28    Male      Asian   25                        115   

   Blood Pressure (diastolic)  Heart Rate  Respiratory Rate  \
0                          80          75                16   
1                          90          80                18   
2                         100          90                20   
3                          95          70                14   
4                          75          80                16   

   Oxygen Saturation Level Chronic Conditions     Medications  \
0                       98               None            None   
1                       95       Hypertension            None   
2                       92           Diabetes         Insulin   
3                       96               None  Blood thinners   
4                       97               None            None   

  Lab Test Results      Chief Complaint  Severity  
0           Normal           Chest Pain    Severe  
1     High Glucose             Headache  Moderate  
2  Abnormal Sodium  Shortness of Breath    Severe  
3           Normal           Chest Pain  Moderate  
4           Normal                Fever      Mild

In [ ]:
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels in column 'Severity
p['Severity']= label_encoder.fit_transform(p['Severity'])
p['Severity'].unique()

array([2, 1, 0])

In [ ]:
p.isnull().sum()

Age                           0
Gender                        0
Ethnicity                     0
BMI                           0
Blood Pressure (systolic)     0
Blood Pressure (diastolic)    0
Heart Rate                    0
Respiratory Rate              0
Oxygen Saturation Level       0
Chronic Conditions            0
Medications                   0
Lab Test Results              0
Chief Complaint               0
Severity                      0
dtype: int64

In [ ]:
q=p.select_dtypes(exclude=["object"])

In [ ]:
q.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         22 non-null     int64
 1   BMI                         22 non-null     int64
 2   Blood Pressure (systolic)   22 non-null     int64
 3   Blood Pressure (diastolic)  22 non-null     int64
 4   Heart Rate                  22 non-null     int64
 5   Respiratory Rate            22 non-null     int64
 6   Oxygen Saturation Level     22 non-null     int64
 7   Severity                    22 non-null     int64
dtypes: int64(8)
memory usage: 1.5 KB


In [ ]:
x=q.drop(columns="Severity")
y=q["Severity"]

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [ ]:
# Data Scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(x_train)
X_test_scaled=scaler.transform(x_test)

In [ ]:
model=LogisticRegression()
model.fit(X_train_scaled,y_train)
predict=model.predict(X_test_scaled)

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [ ]:
#confusion matrix
print(confusion_matrix(y_test,predict))

[[2 1 0]
 [0 1 0]
 [2 0 1]]


In [ ]:
print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           0       0.50      0.67      0.57         3
           1       0.50      1.00      0.67         1
           2       1.00      0.33      0.50         3

    accuracy                           0.57         7
   macro avg       0.67      0.67      0.58         7
weighted avg       0.71      0.57      0.55         7



In [ ]:
!pip install auto-sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 42.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 57.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 47.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 260.9/260.9 KB 15.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 63.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 KB 4.2 MB/s eta 0:00:00
  Created wheel for auto-sklearn: filename=auto_sklearn-0.15.0-py3-none-any.whl size=6641946 sha256=a78ab853093be32361520b3a927b1ef3d67607115b9d0c16f604d015790d21f6

In [ ]:
!pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for sklearn: filename=sklearn-0.0.post1-py3-none-any.whl size=2955 sha256=4b4c542afe53c766176cce005f8cd3ad45370cb57d8c7e10c4bee211925b84a2
  Stored in directory: /root/.cache/pip/wheels/f8/e0/3d/9d0c2020c44a519b9f02ab4fa6d2a4a996c98d79ab2f569fa1
Successfully built sklearn


In [ ]:
import joblib

In [ ]:
pip install imblearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 64.8 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.24.2
    Uninstalling scikit-learn-0.24.2:
      Successfully uninstalled scikit-learn-0.24.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
auto-sklearn 0.15.0 requires scikit-learn<0.25.0,>=0.24.0, but you have scikit-learn 1.2.2 which is incompatible.


In [ ]:
import autosklearn.classification
l=autosklearn.classification.AutoSklearnClassifier(time_left_for_this_task=3*60,per_run_time_limit=30)
l.fit(X_train_scaled,y_train)
pred=l.predict(X_test_scaled)

Exception ignored on calling ctypes callback function: <function ThreadpoolController._find_libraries_with_dl_iterate_phdr.<locals>.match_library_callback at 0x7f1f7b19daf0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/threadpoolctl.py", line 584, in match_library_callback
    self._make_controller_from_path(filepath)
  File "/usr/local/lib/python3.9/dist-packages/threadpoolctl.py", line 725, in _make_controller_from_path
    lib_controller = lib_controller_class(
  File "/usr/local/lib/python3.9/dist-packages/threadpoolctl.py", line 810, in __init__
    self._dynlib = ctypes.CDLL(filepath, mode=_RTLD_NOLOAD)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen() error


In [ ]:

l.sprint_statistics

<bound method AutoSklearnEstimator.sprint_statistics of AutoSklearnClassifier(ensemble_class=<class 'autosklearn.ensembles.ensemble_selection.EnsembleSelection'>,
                      per_run_time_limit=30, time_left_for_this_task=180)>

In [ ]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
mae=mean_absolute_error(y_test,pred)
mse=mean_squared_error(y_test,pred)

In [ ]:
print(mae)
print(mse)

0.7142857142857143
1.2857142857142858


In [ ]:
l.leaderboard()

rank  ensemble_weight                type  cost  duration
model_id                                                           
3            1             0.06       random_forest   0.2  1.875114
8            2             0.06         extra_trees   0.2  1.932007
18           3             0.10                 mlp   0.2  1.042678
19           4             0.06                 mlp   0.2  0.904069
5            5             0.10  passive_aggressive   0.4  0.943455
9            6             0.10       random_forest   0.4  2.022549
10           7             0.06       random_forest   0.4  2.126060
14           8             0.02                 mlp   0.4  1.321861
15           9             0.02       random_forest   0.4  1.840259
20          10             0.02       random_forest   0.4  2.065855
2           11             0.06       random_forest   0.6  3.834225
4           12             0.10       random_forest   0.6  1.751805
6           13             0.04                 lda   0.6  0.974421
13          14             0.08       random_forest   0.6  1.810777
17          15             0.12       random_forest   0.6  1.738761

In [ ]:
from sklearn.svm import SVC
#support vector classifier
svc = SVC()
svc.fit(X_train_scaled,y_train)

SVC()

In [ ]:
predict= model.predict(X_test_scaled)
predict

array([1, 0, 1, 0, 1, 2, 0])

In [ ]:
print(classification_report(y_test,predict))
print(confusion_matrix(y_test,predict))

              precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.33      1.00      0.50         1
           2       0.00      0.00      0.00         3

    accuracy                           0.43         7
   macro avg       0.33      0.56      0.39         7
weighted avg       0.33      0.43      0.36         7

[[2 0 1]
 [0 1 0]
 [1 2 0]]
